security:
    providers:
         chain_provider:
            chain:
                providers: [main ]
         main:
            entity:
                class: AppBundle\Entity\Usuario
                property: correo


    encoders:
        AppBundle\Entity\Usuario: bcrypt

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false
        backend:

            pattern:    ^/
            anonymous: ~
            provider: chain_provider
            form_login:
                login_path:  login
                check_path:  login_check
                default_target_path: redireccionar
                always_use_default_target_path: true
            logout:
                path:   /logout
                target: /
    access_control:
        - { path:^/login, roles:IS_AUTHENTICATED_ANONYMOUSLY}
        #- { path:^/usuario, roles:ROLE_ADMIN}
        - { path:^/usuario, roles: ROLE_ADMIN}
        - { path:^/documento, roles: [ROLE_ADMIN,ROLE_PROFESOR]}
        - { path:^/clave, roles: ROLE_ADMIN}
        - { path:^/empresa, roles: ROLE_ADMIN}
        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
        #- { path: ^/_internal/secure, roles: IS_AUTHENTICATED_ANONYMOUSLY, ip: 127.0.0.1 }
