codigo_index:
    path:     /
    defaults: { _controller: "AppBundle:Codigo:index" }
    methods:  GET

codigo_show:
    path:     /{id}/show
    defaults: { _controller: "AppBundle:Codigo:show" }
    methods:  GET

codigo_new:
    path:     /new
    defaults: { _controller: "AppBundle:Codigo:new" }
    methods:  [GET, POST]

codigo_edit:
    path:     /{id}/edit
    defaults: { _controller: "AppBundle:Codigo:edit" }
    methods:  [GET, POST]

codigo_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppBundle:Codigo:delete" }

