dato_index:
    path:     /
    defaults: { _controller: "AppBundle:Dato:index" }
    methods:  GET

dato_show:
    path:     /{id}/show
    defaults: { _controller: "AppBundle:Dato:show" }
    methods:  GET

dato_new:
    path:     /new
    defaults: { _controller: "AppBundle:Dato:new" }
    methods:  [GET, POST]

dato_edit:
    path:     /{id}/edit
    defaults: { _controller: "AppBundle:Dato:edit" }
    methods:  [GET, POST]

dato_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppBundle:Dato:delete" }
    methods:  DELETE
