<?php

namespace Proxies\__CG__\AppBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Factura extends \AppBundle\Entity\Factura implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\Factura' . "\0" . 'id', '' . "\0" . 'AppBundle\\Entity\\Factura' . "\0" . 'fecha', '' . "\0" . 'AppBundle\\Entity\\Factura' . "\0" . 'nombcliente', '' . "\0" . 'AppBundle\\Entity\\Factura' . "\0" . 'nombempresa', '' . "\0" . 'AppBundle\\Entity\\Factura' . "\0" . 'nombvendedor', '' . "\0" . 'AppBundle\\Entity\\Factura' . "\0" . 'direcmpresa', '' . "\0" . 'AppBundle\\Entity\\Factura' . "\0" . 'telecmpresa', '' . "\0" . 'AppBundle\\Entity\\Factura' . "\0" . 'nota', '' . "\0" . 'AppBundle\\Entity\\Factura' . "\0" . 'listsize', '' . "\0" . 'AppBundle\\Entity\\Factura' . "\0" . 'idioma', '' . "\0" . 'AppBundle\\Entity\\Factura' . "\0" . 'moneda', '' . "\0" . 'AppBundle\\Entity\\Factura' . "\0" . 'productoid', '' . "\0" . 'AppBundle\\Entity\\Factura' . "\0" . 'tipoid'];
        }

        return ['__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\Factura' . "\0" . 'id', '' . "\0" . 'AppBundle\\Entity\\Factura' . "\0" . 'fecha', '' . "\0" . 'AppBundle\\Entity\\Factura' . "\0" . 'nombcliente', '' . "\0" . 'AppBundle\\Entity\\Factura' . "\0" . 'nombempresa', '' . "\0" . 'AppBundle\\Entity\\Factura' . "\0" . 'nombvendedor', '' . "\0" . 'AppBundle\\Entity\\Factura' . "\0" . 'direcmpresa', '' . "\0" . 'AppBundle\\Entity\\Factura' . "\0" . 'telecmpresa', '' . "\0" . 'AppBundle\\Entity\\Factura' . "\0" . 'nota', '' . "\0" . 'AppBundle\\Entity\\Factura' . "\0" . 'listsize', '' . "\0" . 'AppBundle\\Entity\\Factura' . "\0" . 'idioma', '' . "\0" . 'AppBundle\\Entity\\Factura' . "\0" . 'moneda', '' . "\0" . 'AppBundle\\Entity\\Factura' . "\0" . 'productoid', '' . "\0" . 'AppBundle\\Entity\\Factura' . "\0" . 'tipoid'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Factura $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getFecha()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFecha', []);

        return parent::getFecha();
    }

    /**
     * {@inheritDoc}
     */
    public function setFecha($fecha)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFecha', [$fecha]);

        return parent::setFecha($fecha);
    }

    /**
     * {@inheritDoc}
     */
    public function getNombcliente()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNombcliente', []);

        return parent::getNombcliente();
    }

    /**
     * {@inheritDoc}
     */
    public function setNombcliente($nombcliente)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNombcliente', [$nombcliente]);

        return parent::setNombcliente($nombcliente);
    }

    /**
     * {@inheritDoc}
     */
    public function getNombempresa()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNombempresa', []);

        return parent::getNombempresa();
    }

    /**
     * {@inheritDoc}
     */
    public function setNombempresa($nombempresa)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNombempresa', [$nombempresa]);

        return parent::setNombempresa($nombempresa);
    }

    /**
     * {@inheritDoc}
     */
    public function getNombvendedor()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNombvendedor', []);

        return parent::getNombvendedor();
    }

    /**
     * {@inheritDoc}
     */
    public function setNombvendedor($nombvendedor)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNombvendedor', [$nombvendedor]);

        return parent::setNombvendedor($nombvendedor);
    }

    /**
     * {@inheritDoc}
     */
    public function getDirecmpresa()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDirecmpresa', []);

        return parent::getDirecmpresa();
    }

    /**
     * {@inheritDoc}
     */
    public function setDirecmpresa($direcmpresa)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDirecmpresa', [$direcmpresa]);

        return parent::setDirecmpresa($direcmpresa);
    }

    /**
     * {@inheritDoc}
     */
    public function getTelecmpresa()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTelecmpresa', []);

        return parent::getTelecmpresa();
    }

    /**
     * {@inheritDoc}
     */
    public function setTelecmpresa($telecmpresa)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTelecmpresa', [$telecmpresa]);

        return parent::setTelecmpresa($telecmpresa);
    }

    /**
     * {@inheritDoc}
     */
    public function getNota()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNota', []);

        return parent::getNota();
    }

    /**
     * {@inheritDoc}
     */
    public function setNota($nota)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNota', [$nota]);

        return parent::setNota($nota);
    }

    /**
     * {@inheritDoc}
     */
    public function getListsize()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getListsize', []);

        return parent::getListsize();
    }

    /**
     * {@inheritDoc}
     */
    public function setListsize($listsize)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setListsize', [$listsize]);

        return parent::setListsize($listsize);
    }

    /**
     * {@inheritDoc}
     */
    public function getProductoid()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProductoid', []);

        return parent::getProductoid();
    }

    /**
     * {@inheritDoc}
     */
    public function setProductoid($productoid)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setProductoid', [$productoid]);

        return parent::setProductoid($productoid);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdioma()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdioma', []);

        return parent::getIdioma();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdioma($idioma)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdioma', [$idioma]);

        return parent::setIdioma($idioma);
    }

    /**
     * {@inheritDoc}
     */
    public function getSizeid()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSizeid', []);

        return parent::getSizeid();
    }

    /**
     * {@inheritDoc}
     */
    public function setSizeid($sizeid)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSizeid', [$sizeid]);

        return parent::setSizeid($sizeid);
    }

    /**
     * {@inheritDoc}
     */
    public function getTipoid()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTipoid', []);

        return parent::getTipoid();
    }

    /**
     * {@inheritDoc}
     */
    public function setTipoid($tipoid)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTipoid', [$tipoid]);

        return parent::setTipoid($tipoid);
    }

    /**
     * {@inheritDoc}
     */
    public function getMoneda()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMoneda', []);

        return parent::getMoneda();
    }

    /**
     * {@inheritDoc}
     */
    public function setMoneda($moneda)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMoneda', [$moneda]);

        return parent::setMoneda($moneda);
    }

    /**
     * {@inheritDoc}
     */
    public function __toString()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__toString', []);

        return parent::__toString();
    }

}
